language: node_js
node_js:
- 14
script:
- yarn lint
- yarn test
cache: yarn
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  on:
    branch: master
  github_token:
    secure: kkLePsyqF2LSuMc0tvwlANnLdO+jUDBRVQqq+6oB3y5vPwL3Sxmzy9h5IqDd/pYrcnvH8bN6R/3rLdGueBOBSTA/JoaNs9M7F2lMJgE6FiuAxfbAK3epkF8kagB4e5GAp2hJXOFQAk5eqA3rBWSOUrKWzYaBu36nt9lduiaRVPDiU97/PPv6aVXcc2nivFX/GmZLZ8t6eoAN6LF8FOGWQ/QBcx5IAI8rqTeObRe8OJjQf02R6Tepmi8Jy09yszyHClnbpaDseJ3KV2Mw0vaPB9fQN8lCUHq3S81JNCEZLZR6/lFXv2niUAL8QmBw7vMB0xQE11PxxvlvI5+X7DbmanTfP1xANOzdEMTfdMKpUsJ/Qi1nE6IcaWrNjxts+fvcsJrDcV0j8kouFJsjPU1Grb+lWDMzFUdliUbAK7iTKk19F9f8+sE1fyjmQM4ZW5pl4c1g0OSFznK57X6F3zwh3Fx1zwUG1vrUXZ2fCIE0D0hMqbCXnmkIuE2uX8FlobRgKtb0z1080P0XcJ8LJWz4U82Yyo9I7FaaW0tTMQnbT8Elng6lmnY59W/VAlw4Myn/cxkxR6mplt3lNXzNrThgHLvjfsUdTd6QCARPQYcaWWVr1b2qc5e+9+wCiCA5QIuqD46uYuRsHeP4aEN7299MYyTN6ubI/75uW1gYUShyvZk=

